### ISSUE TITLE
Use bioversions to get MONDO version

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/disease-normalization#103]
We are retrieving the latest version from [bioversions](https://github.com/biopragmatics/bioversions) which pulls the from [bioregistry](https://github.com/biopragmatics/bioregistry). bioregistry currently stores the latest version as `2022-12-01`. However, the latest version is actually `20223-01-04` as seen in MONDO's latest releases [here](https://github.com/monarch-initiative/mondo/releases). I need to do a deeper dive on how bioregistry gets the latest version for mondo to create an issue/PR, but for now we can use GitHub's API.

To get the correct latest version, we can do:
```python
import requests

response = requests.get("https://api.github.com/repos/monarch-initiative/mondo/releases/latest")
self._version = response.json()["name"].replace("v", "")
```

We could also replace the download url with if we wanted to ensure that the latest release is always being downloaded. The current url works, but might be safer to change in the event that there is a mismatch (seems unlikely?):

```python
url = f"http://purl.obolibrary.org/obo/mondo/releases/{self._version}/mondo.owl"
```

**Comment by korikuzma** [comment]
Merged a temporary solution. Will revert back to using bioversions to get the version once the issue is resolved in bioregistry

**Comment by cthoyt** [comment]
hey @korikuzma, bioregistry pulls versions from OLS. Since they're migrating from the OLS3 to OLS4, they had to pull a recent MONDO release. Should be back up soon!

**Comment by korikuzma** [comment]
@cthoyt thanks!

**Comment by korikuzma** [comment]
Closing since we will be removing bioversions dependency in #141
