### ISSUE TITLE
Update pydantic to v2 + remove ga4gh.vrsatile.pydantic dependency

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/disease-normalization#135]
We technically don't need to have any direct dependencies on VRS-Python, but we need to ship a Pydantic 2.x compatible version to enable usage in integrated contexts like metakb

**Comment by korikuzma** [comment]
I will be updating the gk pilot data this week and will need to do this

**Comment by korikuzma** [comment]
Initial work on [issue-35 branch](https://github.com/cancervariants/disease-normalization/tree/issue-135). Going to use locally with metakb changes. Once we confirm it works, I'll make a PR for this
