### ISSUE TITLE
Normalized concepts are borked

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/disease-normalization#201]
I'm not allocated to handle this in the immediate term, but it appears that something about xrefs and/or merged concept generation is wrong, because lots of groups (eg neuroblastoma) are missing members in the latest run I've done locally. Should be resolved before we do any data updates on the production servers.

**Comment by korikuzma** [comment]
Could this be caused by #197 ? I'd like to update the DDB sometime next week. I can try to look into this
