### ISSUE TITLE
Unable to normalize MetaKB terms

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/disease-normalization#77]
In the analysis of MetaKB, we were unable to normalize these terms for a disease in MOA. This resulted in us not being able to capture 6 MOA assertions. 
```
oncotree:TALL
T-Cell Acute Lymphoid Leukemia
T-Cell Acute Lymphoid Leukemia
```

It might belong in [this](http://normalize.cancervariants.org/disease/normalize?q=ncit:C3183) concept group, but I might be wrong.

**Comment by jsstevenson** [comment]
I think this is a combo of a) using deprecated data and b) using a nonstandard (possibly erroneous?) term.

This is probably the oncotree entry they're referring to:

```
  {
    "code": "TLL",
    "color": "LimeGreen",
    "name": "T-Lymphoblastic Leukemia/Lymphoma",
    "mainType": "T-Lymphoblastic Leukemia/Lymphoma",
    "externalReferences": {},
    "tissue": "Lymphoid",
    "children": {},
    "parent": "LNM",
    "history": [],
    "level": 3,
    "revocations": [
      "ALL"
    ],
    "precursors": [
      "TALL"
    ]
  },
```

That being said, we'd probably prefer to hook into the MONDO entry (linked above) rather than settling for the Oncotree code, which would mean using code `T-ALL` or using `lymphoblastic` in place of `lymphoid`.

**Comment by korikuzma** [comment]
@jsstevenson sadly this is the only data we have in MOA:

```json
        "disease": {
            "name": "T-Cell Acute Lymphoid Leukemia",
            "oncotree_code": "TALL",
            "oncotree_term": "T-Cell Acute Lymphoid Leukemia"
        }
```

**Comment by jsstevenson** [comment]
Yeah, I would say our options are a) ask for an update in MOA, b) manually redirect (either in MetaKB or in Disease Norm) or c) live with it

**Comment by jsstevenson** [comment]
We think this is https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&code=C3183&ns=ncit
